/// Exact-ID reference from FFR_Ability_Source_Breakdown.pdf (October 1, 2026).
/// PDF SHA-256: a1b03c0604edad71bc085d10d2d06a9683b7892eadeb43018361e1676c90b775.
/// Covers its 303 tier abilities, 27 Resonances and 305 passives (pages 2–38).
/// One representative owner per ID; shared entries can have other owners.
/// The 24 rows without assignments are omitted. Six internal labels are qualified.
/// Awakening comes only from an explicit tier, never a bond or linked variant.
/// Display metadata only: this reference must not drive visibility or verification.
class CatalogSourceReference {
  const CatalogSourceReference(
    this.owner, {
    this.awakening,
    this.internalLabelOnly = false,
  });
  final String owner;
  final int? awakening;
  final bool internalLabelOnly;
}

// Keep the reference rows together for comparison with the PDF.
// dart format off
const catalogSourceReferences = <String, Map<int, CatalogSourceReference>>{
  'skills': {
    // Studio tier abilities, PDF page 2.
    300380: CatalogSourceReference("Siren"), // (召喚獣用)エアロガ全体化 (Esper)
    220170: CatalogSourceReference("Onion Knight", awakening: 1), // Aero (Vision)
    225120: CatalogSourceReference("Victoria"), // Aero (Vision)
    250170: CatalogSourceReference("Aether’s Minion"), // Aero (Monster)
    255120: CatalogSourceReference("Aether’s Guardian"), // Aero (Monster)
    420130: CatalogSourceReference("Bartz", awakening: 1), // Aero Blade (Vision)
    220460: CatalogSourceReference("Y’shtola", awakening: 2), // Aero II of the Seventh Dawn (Vision)
    220470: CatalogSourceReference("Y’shtola", awakening: 3), // Aero III of the Seventh Dawn (Vision)
    421250: CatalogSourceReference("Firion", awakening: 1), // Aero Knife (Vision)
    220450: CatalogSourceReference("Y’shtola", awakening: 1), // Aero of the Seventh Dawn (Vision)
    421310: CatalogSourceReference("Clive", awakening: 1), // Aero Surge (Vision)
    220190: CatalogSourceReference("Onion Knight", awakening: 3), // Aeroga (Vision)
    225140: CatalogSourceReference("Victoria"), // Aeroga (Vision)
    420150: CatalogSourceReference("Bartz", awakening: 3), // Aeroga Blade (Vision)
    421270: CatalogSourceReference("Firion", awakening: 3), // Aeroga Knife (Vision)
    421330: CatalogSourceReference("Clive", awakening: 3), // Aeroga Surge (Vision)
    220180: CatalogSourceReference("Onion Knight", awakening: 2), // Aerora (Vision)
    // Studio tier abilities, PDF page 3.
    225130: CatalogSourceReference("Victoria"), // Aerora (Vision)
    420140: CatalogSourceReference("Bartz", awakening: 2), // Aerora Blade (Vision)
    421260: CatalogSourceReference("Firion", awakening: 2), // Aerora Knife (Vision)
    421320: CatalogSourceReference("Clive", awakening: 2), // Aerora Surge (Vision)
    400450: CatalogSourceReference("Amelia"), // Aim (Vision)
    414410: CatalogSourceReference("Camille", awakening: 3), // Aquatic Synergy (Vision)
    210150: CatalogSourceReference("Ayaka", awakening: 3), // Arise (Vision)
    400650: CatalogSourceReference("Firion"), // Arms Akimbo (Vision)
    210250: CatalogSourceReference("Leah", awakening: 1), // Banish (Vision)
    225290: CatalogSourceReference("Leah"), // Banish (Vision)
    240230: CatalogSourceReference("Tegmine"), // Banish (Monster)
    245290: CatalogSourceReference("Tegmine"), // Banish (Monster)
    420330: CatalogSourceReference("Cecil", awakening: 1), // Banish Blade (Vision)
    210270: CatalogSourceReference("Leah", awakening: 3), // Banishga (Vision)
    420350: CatalogSourceReference("Cecil", awakening: 3), // Banishga Blade (Vision)
    210260: CatalogSourceReference("Leah", awakening: 2), // Banishra (Vision)
    225300: CatalogSourceReference("Leah"), // Banishra (Vision)
    240240: CatalogSourceReference("Tegmine"), // Banishra (Monster)
    // Studio tier abilities, PDF page 4.
    245300: CatalogSourceReference("Sadalsuud"), // Banishra (Monster)
    420340: CatalogSourceReference("Cecil", awakening: 2), // Banishra Blade (Vision)
    400300: CatalogSourceReference("Noctis"), // Barrage (Vision)
    230170: CatalogSourceReference("Vaan", awakening: 3), // Berserk (Vision)
    220260: CatalogSourceReference("Tronn", awakening: 4), // Bio (Vision)
    225190: CatalogSourceReference("Siren"), // Bio (Esper)
    255190: CatalogSourceReference("Brachium"), // Bio (Monster)
    400350: CatalogSourceReference("Camille"), // Blade Dance (Vision)
    445200: CatalogSourceReference("Onion Knight", awakening: 3), // Blade Torrent (Vision)
    400310: CatalogSourceReference("Firion"), // Bladeblitz (Vision)
    230020: CatalogSourceReference("Tronn", awakening: 1), // Blind (Vision)
    422030: CatalogSourceReference("Firion", awakening: 2), // Blind Knife (Vision)
    235010: CatalogSourceReference("Aqua Elemental"), // Blindga (Monster)
    220070: CatalogSourceReference("Noctis", awakening: 3), // Blizzaga (Vision)
    225050: CatalogSourceReference("Tronn"), // Blizzaga (Vision)
    420060: CatalogSourceReference("Lasswell", internalLabelOnly: true), // Blizzaga Blade (Character)
    421390: CatalogSourceReference("Aileen", awakening: 3), // Blizzaga Surge (Vision)
    220060: CatalogSourceReference("Noctis", awakening: 2), // Blizzara (Vision)
    // Studio tier abilities, PDF page 5.
    225040: CatalogSourceReference("Shiva"), // Blizzara (Esper)
    420050: CatalogSourceReference("Lasswell", internalLabelOnly: true), // Blizzara Blade (Character)
    421380: CatalogSourceReference("Aileen", awakening: 2), // Blizzara Surge (Vision)
    220050: CatalogSourceReference("Noctis", awakening: 1), // Blizzard (Vision)
    225030: CatalogSourceReference("Tronn"), // Blizzard (Vision)
    250050: CatalogSourceReference("Tronn"), // Blizzard (Vision)
    255030: CatalogSourceReference("Sergeant"), // Blizzard (Monster)
    420040: CatalogSourceReference("Lasswell", internalLabelOnly: true), // Blizzard Blade (Character)
    220430: CatalogSourceReference("Y’shtola", awakening: 2), // Blizzard II of the Seventh Dawn (Vision)
    220440: CatalogSourceReference("Y’shtola", awakening: 3), // Blizzard III of the Seventh Dawn (Vision)
    220420: CatalogSourceReference("Y’shtola", awakening: 1), // Blizzard of the Seventh Dawn (Vision)
    421370: CatalogSourceReference("Aileen", awakening: 1), // Blizzard Surge (Vision)
    446300: CatalogSourceReference("Sephiroth", awakening: 1), // Boundless Void (Vision)
    446000: CatalogSourceReference("Cloud", awakening: 2), // Braver (Vision)
    230100: CatalogSourceReference("Camille", awakening: 1), // Bravery (Vision)
    220240: CatalogSourceReference("Aldhafera"), // Calamity (Monster)
    220120: CatalogSourceReference("Aldhafera"), // Chain Spark (Monster)
    400440: CatalogSourceReference("Wilhelm"), // Chakra (Vision)
    // Studio tier abilities, PDF page 6.
    230180: CatalogSourceReference("Tronn", awakening: 4), // Confuse (Vision)
    400380: CatalogSourceReference("Cecil"), // Cover (Vision)
    446010: CatalogSourceReference("Cloud", awakening: 3), // Cross-Slash (Vision)
    445500: CatalogSourceReference("Bartz", awakening: 2), // Crushing Blade (Vision)
    414800: CatalogSourceReference("Aileen", awakening: 2), // Crust Driver (Vision)
    210020: CatalogSourceReference("Ayaka", awakening: 2), // Cura (Vision)
    215010: CatalogSourceReference("Leah"), // Cura (Vision)
    210030: CatalogSourceReference("Ayaka", awakening: 3), // Curaga (Vision)
    215020: CatalogSourceReference("Leah"), // Curaga (Vision)
    210010: CatalogSourceReference("Ayaka", awakening: 1), // Cure (Vision)
    215000: CatalogSourceReference("Leah"), // Cure (Vision)
    240010: CatalogSourceReference("Leah"), // Cure (Vision)
    245000: CatalogSourceReference("Mandragora"), // Cure (Monster)
    220490: CatalogSourceReference("Y’shtola", awakening: 2), // Cure II of the Seventh Dawn (Vision)
    220500: CatalogSourceReference("Y’shtola", awakening: 3), // Cure III of the Seventh Dawn (Vision)
    220480: CatalogSourceReference("Y’shtola", awakening: 1), // Cure of the Seventh Dawn (Vision)
    220160: CatalogSourceReference("Aldhafera"), // Cyclone Wave (Monster)
    414700: CatalogSourceReference("Wilhelm", awakening: 2), // D Sword Breaker (Vision)
    // Studio tier abilities, PDF page 7.
    220390: CatalogSourceReference("Victoria", awakening: 1), // Dark (Vision)
    420300: CatalogSourceReference("Cecil", awakening: 1), // Dark Blade (Vision)
    422050: CatalogSourceReference("Sephiroth", awakening: 1), // Dark Surge (Vision)
    220400: CatalogSourceReference("Victoria", awakening: 3), // Darkga (Vision)
    420320: CatalogSourceReference("Cecil", awakening: 3), // Darkga Blade (Vision)
    422070: CatalogSourceReference("Sephiroth", awakening: 3), // Darkga Surge (Vision)
    400490: CatalogSourceReference("Cecil"), // Darkness (Vision)
    220520: CatalogSourceReference("Victoria", awakening: 2), // Darkra (Vision)
    420310: CatalogSourceReference("Cecil", awakening: 2), // Darkra Blade (Vision)
    422060: CatalogSourceReference("Sephiroth", awakening: 2), // Darkra Surge (Vision)
    220320: CatalogSourceReference("Shantotto", awakening: 3), // Death (Vision)
    400530: CatalogSourceReference("Cloud"), // Deathblow (Vision)
    230190: CatalogSourceReference("Cloud", awakening: 1), // Debrave (Vision)
    230200: CatalogSourceReference("Abhorrent One"), // Defaith (Monster)
    400010: CatalogSourceReference("Archwitch Fina"), // Defend (Character)
    230080: CatalogSourceReference("Amelia", awakening: 1), // Deprotect (Vision)
    230090: CatalogSourceReference("Amelia", awakening: 2), // Deshell (Vision)
    414210: CatalogSourceReference("Amelia", awakening: 3), // Disorder (Vision)
    // Studio tier abilities, PDF page 8.
    210200: CatalogSourceReference("Ayaka", awakening: 1), // Dispel (Vision)
    210210: CatalogSourceReference("Nichol"), // Dispelga (Character)
    400710: CatalogSourceReference("Squall"), // Double Action (Vision)
    220300: CatalogSourceReference("Lightning", awakening: 2), // Drain (Vision)
    250300: CatalogSourceReference("Aether’s Minion"), // Drain (Monster)
    422040: CatalogSourceReference("Firion", awakening: 3), // Drain Knife (Vision)
    445210: CatalogSourceReference("Onion Knight", awakening: 4), // Dual Jobs (Vision)
    400730: CatalogSourceReference("Shantotto"), // Dualcast (Vision)
    447010: CatalogSourceReference("Tidus", awakening: 3), // Energy Rain (Vision)
    210120: CatalogSourceReference("Ayaka", awakening: 1), // Esuna (Vision)
    210130: CatalogSourceReference("Ayaka", awakening: 4), // Esunaga (Vision)
    230110: CatalogSourceReference("Shantotto", awakening: 1), // Faith (Vision)
    446610: CatalogSourceReference("Squall", awakening: 3), // Fated Circle (Vision)
    400770: CatalogSourceReference("Cloud"), // Fill Gauge (Vision)
    220020: CatalogSourceReference("Amelia", awakening: 2), // Fira (Vision)
    225010: CatalogSourceReference("Ifrit"), // Fira (Esper)
    420020: CatalogSourceReference("Lasswell", internalLabelOnly: true), // Fira Blade (Character)
    421020: CatalogSourceReference("Vaan", awakening: 2), // Fira Slam (Vision)
    // Studio tier abilities, PDF page 9.
    421050: CatalogSourceReference("Clive", awakening: 2), // Fira Surge (Vision)
    220030: CatalogSourceReference("Amelia", awakening: 3), // Firaga (Vision)
    225020: CatalogSourceReference("Amelia"), // Firaga (Vision)
    420030: CatalogSourceReference("Lasswell", internalLabelOnly: true), // Firaga Blade (Character)
    421030: CatalogSourceReference("Vaan", awakening: 3), // Firaga Slam (Vision)
    421060: CatalogSourceReference("Clive", awakening: 3), // Firaga Surge (Vision)
    220010: CatalogSourceReference("Amelia", awakening: 1), // Fire (Vision)
    225000: CatalogSourceReference("Amelia"), // Fire (Vision)
    250010: CatalogSourceReference("Tronn"), // Fire (Vision)
    255000: CatalogSourceReference("Red Roper"), // Fire (Monster)
    420010: CatalogSourceReference("Lasswell", internalLabelOnly: true), // Fire Blade (Character)
    421010: CatalogSourceReference("Vaan", awakening: 1), // Fire Slam (Vision)
    421040: CatalogSourceReference("Clive", awakening: 1), // Fire Surge (Vision)
    400550: CatalogSourceReference("Leah"), // First Aid (Vision)
    220330: CatalogSourceReference("Onion Knight", awakening: 4), // Flare (Vision)
    420270: CatalogSourceReference("Bartz", awakening: 4), // Flare Blade (Vision)
    400460: CatalogSourceReference("Tidus"), // Focus (Vision)
    400630: CatalogSourceReference("Tronn"), // Focus Magic (Vision)
    // Studio tier abilities, PDF page 10.
    220510: CatalogSourceReference("Y’shtola", awakening: 4), // Foul of the Seventh Dawn (Vision)
    446800: CatalogSourceReference("Zidane", awakening: 1), // Free Energy (Vision)
    446810: CatalogSourceReference("Zidane", awakening: 3), // Free Energy+ (Vision)
    220080: CatalogSourceReference("Aldhafera"), // Freezing Spike (Monster)
    421070: CatalogSourceReference("Lightning", awakening: 1), // Froststrike (Vision)
    421080: CatalogSourceReference("Lightning", awakening: 2), // Froststrike II (Vision)
    421090: CatalogSourceReference("Lightning", awakening: 3), // Froststrike III (Vision)
    445100: CatalogSourceReference("Firion", awakening: 1), // Fulminating Strike (Vision)
    445120: CatalogSourceReference("Firion", awakening: 4), // Fulminating Strike+ (Vision)
    400400: CatalogSourceReference("Vaan"), // Gil Farmer (Vision)
    400250: CatalogSourceReference("Vaan"), // Gil Toss (Vision)
    220290: CatalogSourceReference("Victoria", awakening: 4), // Graviga (Vision)
    220280: CatalogSourceReference("Victoria", awakening: 3), // Gravity (Vision)
    400640: CatalogSourceReference("Wilhelm"), // Guard (Vision)
    400690: CatalogSourceReference("Squall"), // Gut Rip (Vision)
    230130: CatalogSourceReference("Camille", awakening: 2), // Haste (Vision)
    230140: CatalogSourceReference("Tidus", awakening: 4), // Hastega (Vision)
    448010: CatalogSourceReference("Clive", awakening: 3), // Heatwave (Vision)
    // Studio tier abilities, PDF page 11.
    414510: CatalogSourceReference("Ayaka", awakening: 3), // Hi Regen (Vision)
    // 210190: Holy — no assignment found.
    220040: CatalogSourceReference("Aldhafera"), // Inferno Sphere (Monster)
    400210: CatalogSourceReference("Aileen"), // Jump (Vision)
    400280: CatalogSourceReference("Charlotte"), // Lance (Vision)
    210220: CatalogSourceReference("Aileen", awakening: 1), // Libra (Vision)
    447500: CatalogSourceReference("Lightning", awakening: 2), // Lightning Strike (Vision)
    300010: CatalogSourceReference("Siren"), // Lunatic Voice (Esper)
    400360: CatalogSourceReference("Y’shtola"), // Magic Barrage (Vision)
    400660: CatalogSourceReference("Terra"), // Magic Boost (Vision)
    220410: CatalogSourceReference("Y’shtola", awakening: 2), // Manaward (Vision)
    414810: CatalogSourceReference("Aileen", awakening: 3), // Mantle Driver (Vision)
    300110: CatalogSourceReference("Bahamut"), // Megaflare (Esper)
    220380: CatalogSourceReference("Terra", awakening: 3), // Meltdown (Vision)
    446820: CatalogSourceReference("Zidane", awakening: 2), // Meo Twister (Vision)
    446830: CatalogSourceReference("Zidane", awakening: 4), // Meo Twister+ (Vision)
    220350: CatalogSourceReference("Sephiroth", awakening: 4), // Meteor (Vision)
    400330: CatalogSourceReference("Bartz"), // Mimic (Vision)
    // Studio tier abilities, PDF page 12.
    400500: CatalogSourceReference("Lightning"), // Mineuchi (Vision)
    400670: CatalogSourceReference("Clive"), // Mirage (Vision)
    400750: CatalogSourceReference("Zidane"), // Misfortune (Vision)
    445300: CatalogSourceReference("Cecil", awakening: 3), // Moonlightbringer (Vision)
    400270: CatalogSourceReference("Zidane"), // Mug (Vision)
    400390: CatalogSourceReference("Warrior of Light"), // Multi-Cover (Vision)
    447300: CatalogSourceReference("Shantotto", awakening: 2), // Nightmare Scythe (Vision)
    400680: CatalogSourceReference("Leah"), // Pass the Torch (Vision)
    447800: CatalogSourceReference("Noctis", awakening: 3), // Plunge (Vision)
    220250: CatalogSourceReference("Terra", awakening: 1), // Poison (Vision)
    225180: CatalogSourceReference("Allosaur"), // Poisonga (Monster)
    414600: CatalogSourceReference("Charlotte", awakening: 2), // Power Stagger (Vision)
    400740: CatalogSourceReference("Ayaka"), // Prepare Healing (Vision)
    230040: CatalogSourceReference("Aileen", awakening: 1), // Protect (Vision)
    230050: CatalogSourceReference("Aileen", awakening: 2), // Protectga (Vision)
    446310: CatalogSourceReference("Sephiroth", awakening: 3), // Purging Blade (Vision)
    414500: CatalogSourceReference("Ayaka", awakening: 2), // Purify (Vision)
    210140: CatalogSourceReference("Ayaka", awakening: 2), // Raise (Vision)
    // Studio tier abilities, PDF page 13.
    414200: CatalogSourceReference("Amelia", awakening: 2), // Rapid Fire (Vision)
    400700: CatalogSourceReference("Tidus"), // Reckless Abandonment (Vision)
    400540: CatalogSourceReference("Ayaka"), // Recover (Vision)
    447400: CatalogSourceReference("Vaan", awakening: 2), // Red Spiral (Vision)
    230120: CatalogSourceReference("Aileen", awakening: 4), // Reflect (Vision)
    210050: CatalogSourceReference("Ayaka", awakening: 3), // Regen (Vision)
    210160: CatalogSourceReference("Ayaka", awakening: 4), // Reraise (Vision)
    210240: CatalogSourceReference("Ayaka"), // Reraise (Vision)
    448000: CatalogSourceReference("Clive", awakening: 2), // Rising Flames (Vision)
    446600: CatalogSourceReference("Squall", awakening: 2), // Rough Divide (Vision)
    414610: CatalogSourceReference("Charlotte", awakening: 3), // Royal Guard (Vision)
    445110: CatalogSourceReference("Firion", awakening: 3), // Saber of Adversity (Vision)
    445020: CatalogSourceReference("Warrior of Light", awakening: 3), // Sacred Wave (Vision)
    447310: CatalogSourceReference("Shantotto", awakening: 3), // Salvation Scythe (Vision)
    445310: CatalogSourceReference("Cecil", awakening: 3), // Shadowbringer (Vision)
    230060: CatalogSourceReference("Aileen", awakening: 1), // Shell (Vision)
    230070: CatalogSourceReference("Aileen", awakening: 3), // Shellga (Vision)
    230030: CatalogSourceReference("Squall", awakening: 1), // Silence (Vision)
    // Studio tier abilities, PDF page 14.
    235020: CatalogSourceReference("Blue Elemental"), // Silencega (Monster)
    230010: CatalogSourceReference("Abaddon"), // Sleep (Monster)
    422010: CatalogSourceReference("Firion", awakening: 1), // Sleep Knife (Vision)
    422020: CatalogSourceReference("Vaan", awakening: 2), // Sleep Slam (Vision)
    235000: CatalogSourceReference("Aether’s Minion"), // Sleepga (Monster)
    421220: CatalogSourceReference("Tidus", awakening: 1), // Slice & Dice - Water (Vision)
    421230: CatalogSourceReference("Tidus", awakening: 2), // Slice & Dice - Water II (Vision)
    421240: CatalogSourceReference("Tidus", awakening: 3), // Slice & Dice - Water III (Vision)
    421280: CatalogSourceReference("Tidus", awakening: 1), // Slice & Dice - Wind (Vision)
    421290: CatalogSourceReference("Tidus", awakening: 2), // Slice & Dice - Wind II (Vision)
    421300: CatalogSourceReference("Tidus", awakening: 3), // Slice & Dice - Wind III (Vision)
    230150: CatalogSourceReference("Amelia", awakening: 3), // Slow (Vision)
    230160: CatalogSourceReference("Amelia", awakening: 4), // Slowga (Vision)
    300240: CatalogSourceReference("Siren"), // Sonic Buffet (Esper)
    421160: CatalogSourceReference("Lightning", awakening: 1), // Sparkstrike (Vision)
    421170: CatalogSourceReference("Lightning", awakening: 2), // Sparkstrike II (Vision)
    421180: CatalogSourceReference("Lightning", awakening: 3), // Sparkstrike III (Vision)
    400720: CatalogSourceReference("Victoria"), // Spell Drinker (Vision)
    // Studio tier abilities, PDF page 15.
    414300: CatalogSourceReference("Victoria", awakening: 3), // Spill (Vision)
    447000: CatalogSourceReference("Tidus", awakening: 1), // Spiral Cut (Vision)
    447020: CatalogSourceReference("Tidus", awakening: 3), // Spiral Cut+ (Vision)
    400260: CatalogSourceReference("Zidane"), // Steal (Vision)
    446870: CatalogSourceReference("Zidane", awakening: 3), // Steal Magic (Vision)
    446850: CatalogSourceReference("Zidane", awakening: 1), // Steal Speed (Vision)
    446840: CatalogSourceReference("Zidane", awakening: 1), // Steal Strength (Vision)
    446860: CatalogSourceReference("Zidane", awakening: 2), // Steal Vitality (Vision)
    220210: CatalogSourceReference("Amelia", awakening: 1), // Stone (Vision)
    225150: CatalogSourceReference("Amelia"), // Stone (Vision)
    250210: CatalogSourceReference("Alraune"), // Stone (Monster)
    255150: CatalogSourceReference("Mandragora"), // Stone (Monster)
    420160: CatalogSourceReference("Bartz", awakening: 1), // Stone Blade (Vision)
    421340: CatalogSourceReference("Vaan", awakening: 1), // Stone Slam (Vision)
    421400: CatalogSourceReference("Aileen", awakening: 1), // Stone Surge (Vision)
    220230: CatalogSourceReference("Amelia", awakening: 3), // Stonega (Vision)
    225170: CatalogSourceReference("Amelia"), // Stonega (Vision)
    420180: CatalogSourceReference("Bartz", awakening: 3), // Stonega Blade (Vision)
    // Studio tier abilities, PDF page 16.
    421360: CatalogSourceReference("Vaan", awakening: 3), // Stonega Slam (Vision)
    421420: CatalogSourceReference("Aileen", awakening: 3), // Stonega Surge (Vision)
    220220: CatalogSourceReference("Amelia", awakening: 2), // Stonera (Vision)
    225160: CatalogSourceReference("Titan"), // Stonera (Esper)
    420170: CatalogSourceReference("Bartz", awakening: 2), // Stonera Blade (Vision)
    421350: CatalogSourceReference("Vaan", awakening: 2), // Stonera Slam (Vision)
    421410: CatalogSourceReference("Aileen", awakening: 2), // Stonera Surge (Vision)
    414710: CatalogSourceReference("Wilhelm", awakening: 3), // Supreme Defense (Vision)
    220310: CatalogSourceReference("Lightning", awakening: 3), // Syphon (Vision)
    220200: CatalogSourceReference("Aether"), // Tempest (Monster)
    400240: CatalogSourceReference("Onion Knight"), // Throw (Vision)
    220110: CatalogSourceReference("Noctis", awakening: 3), // Thundaga (Vision)
    225080: CatalogSourceReference("Tronn"), // Thundaga (Vision)
    420090: CatalogSourceReference("Bartz", awakening: 3), // Thundaga Blade (Vision)
    421120: CatalogSourceReference("Firion", awakening: 3), // Thundaga Knife (Vision)
    421150: CatalogSourceReference("Cloud", awakening: 3), // Thundaga Surge (Vision)
    220100: CatalogSourceReference("Noctis", awakening: 2), // Thundara (Vision)
    225070: CatalogSourceReference("Ramuh"), // Thundara (Esper)
    // Studio tier abilities, PDF page 17.
    420080: CatalogSourceReference("Bartz", awakening: 2), // Thundara Blade (Vision)
    421110: CatalogSourceReference("Firion", awakening: 2), // Thundara Knife (Vision)
    421140: CatalogSourceReference("Cloud", awakening: 2), // Thundara Surge (Vision)
    220090: CatalogSourceReference("Noctis", awakening: 1), // Thunder (Vision)
    225060: CatalogSourceReference("Tronn"), // Thunder (Vision)
    250090: CatalogSourceReference("Tronn"), // Thunder (Vision)
    255060: CatalogSourceReference("Tegmine"), // Thunder (Monster)
    420070: CatalogSourceReference("Bartz", awakening: 1), // Thunder Blade (Vision)
    421100: CatalogSourceReference("Firion", awakening: 1), // Thunder Knife (Vision)
    421130: CatalogSourceReference("Cloud", awakening: 1), // Thunder Surge (Vision)
    447510: CatalogSourceReference("Lightning", awakening: 3), // Thunderfall (Vision)
    220360: CatalogSourceReference("Ramuh"), // Thunderspark (Esper)
    300250: CatalogSourceReference("Siren"), // Tornado (Esper)
    414400: CatalogSourceReference("Camille", awakening: 2), // Torrential Hew (Vision)
    220340: CatalogSourceReference("Terra", awakening: 4), // Ultima (Vision)
    445010: CatalogSourceReference("Warrior of Light", awakening: 1), // Vanguard Glaive (Vision)
    445030: CatalogSourceReference("Warrior of Light", awakening: 4), // Vanguard Glaive+ (Vision)
    447810: CatalogSourceReference("Noctis", awakening: 2), // Warp-Strike (Vision)
    // Studio tier abilities, PDF page 18.
    220130: CatalogSourceReference("Shantotto", awakening: 1), // Water (Vision)
    225090: CatalogSourceReference("Terra"), // Water (Vision)
    250130: CatalogSourceReference("Abtu"), // Water (Monster)
    255090: CatalogSourceReference("Shark"), // Water (Monster)
    420100: CatalogSourceReference("Camille", awakening: 1), // Water Blade (Vision)
    421190: CatalogSourceReference("Charlotte", awakening: 1), // Water Surge (Vision)
    220140: CatalogSourceReference("Shantotto", awakening: 2), // Watera (Vision)
    225100: CatalogSourceReference("Terra"), // Watera (Vision)
    420110: CatalogSourceReference("Camille", awakening: 2), // Watera Blade (Vision)
    421200: CatalogSourceReference("Charlotte", awakening: 2), // Watera Surge (Vision)
    220150: CatalogSourceReference("Shantotto", awakening: 3), // Waterga (Vision)
    225110: CatalogSourceReference("Terra"), // Waterga (Vision)
    420120: CatalogSourceReference("Camille", awakening: 3), // Waterga Blade (Vision)
    421210: CatalogSourceReference("Charlotte", awakening: 3), // Waterga Surge (Vision)
    447410: CatalogSourceReference("Vaan", awakening: 3), // White Whorl (Vision)
    445510: CatalogSourceReference("Bartz", awakening: 3), // Wind Cutter Blade (Vision)
    // Studio Resonance options, PDF page 19.
    440280: CatalogSourceReference("Y’shtola"), // Aetherial Wind (Resonance)
    412270: CatalogSourceReference("Victoria"), // Agony (Resonance)
    412330: CatalogSourceReference("Camille"), // Alluvial Undertow (Resonance)
    412510: CatalogSourceReference("Ayaka"), // Angelic Embrace (Resonance)
    440290: CatalogSourceReference("Noctis"), // Armiger Unleashed (Resonance)
    440110: CatalogSourceReference("Cloud"), // Ascension (Resonance)
    440170: CatalogSourceReference("Squall"), // Blasting Zone (Resonance)
    440210: CatalogSourceReference("Tidus"), // Blitz Ace (Resonance)
    440190: CatalogSourceReference("Zidane"), // Climax Edge (Resonance)
    440240: CatalogSourceReference("Shantotto"), // Colossal Shantotto II (Resonance)
    440010: CatalogSourceReference("Warrior of Light"), // Crystal Braver (Resonance)
    412170: CatalogSourceReference("Amelia"), // Errand’s End (Resonance)
    412800: CatalogSourceReference("Aileen"), // Fatal Impact (Resonance)
    414100: CatalogSourceReference("Leah"), // Healing Wind (Resonance)
    414090: CatalogSourceReference("Tronn"), // Hibernal Fury (Resonance)
    440030: CatalogSourceReference("Onion Knight"), // Job Change Attack (Resonance)
    440040: CatalogSourceReference("Cecil"), // Knight of Duality (Resonance)
    // Studio Resonance options, PDF page 20.
    412600: CatalogSourceReference("Charlotte"), // Resolute Bastion (Resonance)
    440090: CatalogSourceReference("Terra"), // Riot Blade - Lotus (Resonance)
    440060: CatalogSourceReference("Bartz"), // Spellblade-Dual Wield-Rapid Fire (Resonance)
    412620: CatalogSourceReference("Wilhelm"), // Towering Rampart (Resonance)
    440310: CatalogSourceReference("Clive"), // True Ifrit-Primed (Resonance)
    440140: CatalogSourceReference("Sephiroth"), // True Octaslash (Resonance)
    440250: CatalogSourceReference("Vaan"), // True Pyroclasm (Resonance)
    440020: CatalogSourceReference("Firion"), // Weaponsmaster (Resonance)
    440260: CatalogSourceReference("Lightning"), // Zantetsuken (Resonance)
    440230: CatalogSourceReference("Tidus"), // エース・オブ・ザ・ブリッツ(全体) (Resonance)
  },
  'passives': {
    // Studio passives, PDF page 21.
    1128: CatalogSourceReference("Firion", awakening: 3), // Add Blind (Vision)
    1237: CatalogSourceReference("Zidane", awakening: 4), // Add Confuse (Vision)
    1131: CatalogSourceReference("Squall", awakening: 1), // Add Deprotect (Vision)
    1132: CatalogSourceReference("Terra", awakening: 1), // Add Deshell (Vision)
    1130: CatalogSourceReference("Death Adder"), // Add Instant Death (Equipment)
    1125: CatalogSourceReference("Zidane", awakening: 2), // Add Poison (Vision)
    1126: CatalogSourceReference("Noctis", awakening: 2), // Add Silence (Vision)
    1127: CatalogSourceReference("Jackpot Gun"), // Add Sleep (Equipment)
    1129: CatalogSourceReference("Camille", awakening: 3), // Add Slow (Vision)
    1468: CatalogSourceReference("Zidane"), // Aggravation (Vision)
    1455: CatalogSourceReference("Ayaka", awakening: 1), // Alabastrine Blessing (Vision)
    1448: CatalogSourceReference("Camille", awakening: 4), // Alluvial Edge (Vision)
    1449: CatalogSourceReference("Camille", awakening: 4), // Alluvial Flourish (Vision)
    1401: CatalogSourceReference("Ayaka"), // Angelic Advocate (Vision)
    1328: CatalogSourceReference("Victoria"), // Arcane Reclamation (Vision)
    1351: CatalogSourceReference("Shantotto"), // Area Effect Adept (Vision)
    1256: CatalogSourceReference("Philosopher’s Stone"), // Auto MP Restore (L) (Equipment)
    // Studio passives, PDF page 22.
    1255: CatalogSourceReference("Mage’s Stone"), // Auto MP Restore (M) (Equipment)
    1254: CatalogSourceReference("Nightbreaker"), // Auto MP Restore (S) (Equipment)
    1076: CatalogSourceReference("Berserker Ring"), // Auto-Berserk (Equipment)
    1489: CatalogSourceReference("Sephiroth", awakening: 2), // Auto-Bravery (Vision)
    1305: CatalogSourceReference("Leah"), // Auto-Cure Ailments (Vision)
    1304: CatalogSourceReference("Terra", awakening: 3), // Auto-Faith (Vision)
    1074: CatalogSourceReference("Camille", awakening: 3), // Auto-Haste (Vision)
    1479: CatalogSourceReference("Circlet of Enlightenment"), // Auto-LB Charge (Equipment)
    // 1043: Auto-Potion — no assignment found.
    1072: CatalogSourceReference("Protect Ring"), // Auto-Protect (Equipment)
    1071: CatalogSourceReference("Alpherg"), // Auto-Reflect (Monster)
    1077: CatalogSourceReference("Firion", awakening: 4), // Auto-Regen (Vision)
    1073: CatalogSourceReference("Charlotte", awakening: 3), // Auto-Shell (Vision)
    1075: CatalogSourceReference("Iron Sandals"), // Auto-Slow (Equipment)
    1454: CatalogSourceReference("Wilhelm", awakening: 4), // Bastion (Vision)
    1335: CatalogSourceReference("Noctis"), // Bonus Damage (Vision)
    1400: CatalogSourceReference("Lightning"), // Bonus Phase Stagger Boost (Vision)
    1460: CatalogSourceReference("Clive", awakening: 1), // Boundless Flames (Vision)
    // Studio passives, PDF page 23.
    1288: CatalogSourceReference("Firion", awakening: 2), // Bravery on Stagger (Vision)
    1294: CatalogSourceReference("Noctis", awakening: 2), // Bravery Opener (Vision)
    1047: CatalogSourceReference("Terra"), // Break the Limit (Vision)
    1420: CatalogSourceReference("Cloud", awakening: 1), // Broadsword Mastery (Vision)
    1412: CatalogSourceReference("Onion Knight", awakening: 3), // Chuck (Vision)
    1442: CatalogSourceReference("Clive", awakening: 3), // Clive’s Limit Break (Vision)
    1487: CatalogSourceReference("Vampire Charm"), // Costly Attack (L) (Equipment)
    1486: CatalogSourceReference("Evil Eye"), // Costly Attack (M) (Equipment)
    1485: CatalogSourceReference("Scar Orb"), // Costly Attack (S) (Equipment)
    // 1488: Costly Attack (XL) — no assignment found.
    // 1484: Costly Stagger (L) — no assignment found.
    1483: CatalogSourceReference("Dark Rosary"), // Costly Stagger (M) (Equipment)
    1482: CatalogSourceReference("Cursed Ring"), // Costly Stagger (S) (Equipment)
    1034: CatalogSourceReference("Abyssal"), // Counter when KO’d (Monster)
    1246: CatalogSourceReference("Orbs of Light"), // Counter when KO’d (Monster)
    1272: CatalogSourceReference("Orbs of Light"), // Counter when KO’d (Monster)
    1234: CatalogSourceReference("Cloud"), // Critical Boost (Vision)
    1333: CatalogSourceReference("Wilhelm"), // Critical Counter (Vision)
    // Studio passives, PDF page 24.
    1247: CatalogSourceReference("Cloud", awakening: 1), // Critical Hit Rate +10% (Vision)
    1480: CatalogSourceReference("Sephiroth", awakening: 3), // Critical Hit Rate +20% (Vision)
    1481: CatalogSourceReference("Sniper’s Eye"), // Critical Hit Rate +30% (Equipment)
    1321: CatalogSourceReference("Wilhelm", awakening: 2), // Critical Hit Rate +5% (Vision)
    1388: CatalogSourceReference("Cloud"), // Critical Stagger (Vision)
    1350: CatalogSourceReference("Sephiroth"), // Dark Eater (Vision)
    1369: CatalogSourceReference("Cecil"), // Dark Immunity (Vision)
    1431: CatalogSourceReference("Shantotto"), // Dark Rite (Vision)
    1457: CatalogSourceReference("Cecil", awakening: 1), // Dark Sword (Vision)
    1102: CatalogSourceReference("Trick Coin"), // Dead Lucky (Equipment)
    1337: CatalogSourceReference("Firion"), // Decimating Attacks (Vision)
    1361: CatalogSourceReference("Noctis", awakening: 3), // Deft Warp (Vision)
    1235: CatalogSourceReference("Warrior of Light", awakening: 2), // Deprotect on Stagger (Vision)
    1296: CatalogSourceReference("Amelia", awakening: 3), // Deprotect Opener (Vision)
    1285: CatalogSourceReference("Tronn", awakening: 3), // Deshell on Stagger (Vision)
    1297: CatalogSourceReference("Amelia", awakening: 3), // Deshell Opener (Vision)
    1056: CatalogSourceReference("Zidane", awakening: 2), // Discerning Eye (Vision)
    1456: CatalogSourceReference("Ayaka", awakening: 4), // Divine Tidings (Vision)
    // Studio passives, PDF page 25.
    1003: CatalogSourceReference("Aldhafera"), // Double Action (unlimited) (Monster)
    1009: CatalogSourceReference("Adept’s Armlet"), // Double EXP (Equipment)
    1050: CatalogSourceReference("Vaan"), // Double Gil (Vision)
    1051: CatalogSourceReference("Mastery Pendant"), // Double MRP (Equipment)
    1341: CatalogSourceReference("Victoria"), // Drop Rate Up (Vision)
    1443: CatalogSourceReference("Amelia", awakening: 1), // Dual Guns (Vision)
    1414: CatalogSourceReference("Bartz"), // Dual Spellblade (Vision)
    // 1346: Earth Eater — no assignment found.
    1365: CatalogSourceReference("Gaia Gear"), // Earth Immunity (Equipment)
    1054: CatalogSourceReference("Foe Attractor"), // Enemy Lure (Equipment)
    1389: CatalogSourceReference("Camille"), // Essence of Mundanity (Vision)
    1295: CatalogSourceReference("Victoria", awakening: 1), // Faith Opener (Vision)
    1478: CatalogSourceReference("Warrior’s Bandana"), // Fill LB on Attack (Equipment)
    // 1324: Fill LB on Critical Hit — no assignment found.
    1320: CatalogSourceReference("Noctis"), // Fill LB on Defeating Foes (Vision)
    1280: CatalogSourceReference("Tronn"), // Fill LB on Stagger (Vision)
    1331: CatalogSourceReference("Firion"), // Fill LB when Taking Damage (Vision)
    1081: CatalogSourceReference("Rudra"), // Fire Counter (Monster)
    // Studio passives, PDF page 26.
    1038: CatalogSourceReference("Clive"), // Fire Eater (Vision)
    1362: CatalogSourceReference("Clive", awakening: 4), // Fire Immunity (Vision)
    // 1010: Fire Weapon — no assignment found.
    1049: CatalogSourceReference("Tidus"), // First Strike (Vision)
    1440: CatalogSourceReference("Y’shtola", awakening: 1), // Fulminating Spells (Vision)
    1452: CatalogSourceReference("Wilhelm", awakening: 1), // General’s Pride (Vision)
    1386: CatalogSourceReference("Vaan"), // Gil Farmer on Stagger (Vision)
    1084: CatalogSourceReference("Ancient Beast Statue"), // Gold-Needle Counter (Monster)
    1042: CatalogSourceReference("Warrior of Light"), // Grit (Vision)
    1259: CatalogSourceReference("Rugged Whip"), // Grit (Equipment)
    1458: CatalogSourceReference("Bartz", awakening: 1), // Guiding Wind (Vision)
    1330: CatalogSourceReference("Charlotte"), // Hale and Hearty (Vision)
    1045: CatalogSourceReference("Tronn"), // Half MP Cost (Vision)
    1053: CatalogSourceReference("Warding Bell"), // Halve Encounters (Equipment)
    1301: CatalogSourceReference("Leah", awakening: 3), // Haste at Half HP (Vision)
    1287: CatalogSourceReference("Vaan", awakening: 3), // Haste on Stagger (Vision)
    1292: CatalogSourceReference("Tidus", awakening: 3), // Haste Opener (Vision)
    1391: CatalogSourceReference("Y’shtola"), // Heal on Sweeping Stagger (Vision)
    // Studio passives, PDF page 27.
    1282: CatalogSourceReference("Leah"), // Healing Magic +10% (Vision)
    1283: CatalogSourceReference("Cecil", awakening: 2), // Healing Magic +20% (Vision)
    1375: CatalogSourceReference("Ayaka", awakening: 1), // Healing Magic +30% (Vision)
    1409: CatalogSourceReference("Warrior of Light"), // Heroic Nature (Vision)
    1334: CatalogSourceReference("Camille"), // Hit and Run (Vision)
    1377: CatalogSourceReference("Heart Anklet"), // HP +10% (Equipment)
    1378: CatalogSourceReference("Cecil", awakening: 3), // HP +20% (Vision)
    1379: CatalogSourceReference("Wilhelm", awakening: 3), // HP +30% (Vision)
    1066: CatalogSourceReference("Bartz"), // HP Stroll (Vision)
    1344: CatalogSourceReference("Charlotte"), // Ice Eater (Vision)
    1363: CatalogSourceReference("Charlotte", awakening: 4), // Ice Immunity (Vision)
    1521: CatalogSourceReference("Solar Pendant"), // Imbue Fire (Equipment)
    1523: CatalogSourceReference("Shock Whip"), // Imbue Lightning (Equipment)
    1421: CatalogSourceReference("Squall"), // Improvement (Vision)
    1402: CatalogSourceReference("Charlotte"), // Indomitable Spirit (Vision)
    1425: CatalogSourceReference("Zidane"), // Insult to Injury (Vision)
    1490: CatalogSourceReference("Sephiroth", awakening: 1), // Jenova Cells (Vision)
    1410: CatalogSourceReference("Onion Knight", awakening: 4), // Job Change (Vision)
    // Studio passives, PDF page 28.
    1463: CatalogSourceReference("Charlotte", awakening: 1), // Knight of the Sacred Frost (Vision)
    1411: CatalogSourceReference("Onion Knight", awakening: 1), // Late Bloomer (Vision)
    1424: CatalogSourceReference("Squall", awakening: 4), // Latent Potential (Vision)
    1397: CatalogSourceReference("Ayaka"), // LB Charge on Heal (Vision)
    1004: CatalogSourceReference("Aileen"), // LB Charge Opener (Vision)
    1000: CatalogSourceReference("Terra"), // LB Double Charge (Vision)
    1403: CatalogSourceReference("Amelia"), // LB Shield (Vision)
    1031: CatalogSourceReference("Onion Knight"), // LB Triple Charge (Vision)
    1357: CatalogSourceReference("Cloud", awakening: 3), // Leaping Cleave (Vision)
    1491: CatalogSourceReference("Sephiroth", awakening: 3), // Legendary SOLDIER (Vision)
    // 1349: Light Eater — no assignment found.
    // 1368: Light Immunity — no assignment found.
    1353: CatalogSourceReference("Firion", awakening: 1), // Light of Rebellion (Vision)
    1347: CatalogSourceReference("Lightning"), // Lightning Eater (Vision)
    1366: CatalogSourceReference("Cloud", awakening: 4), // Lightning Immunity (Vision)
    1423: CatalogSourceReference("Squall", awakening: 4), // Lone Lion (Vision)
    1408: CatalogSourceReference("Warrior of Light", awakening: 3), // Lustrous Shield (Vision)
    1310: CatalogSourceReference("Y’shtola"), // Magic Attack +10% (Vision)
    // Studio passives, PDF page 29.
    1311: CatalogSourceReference("Noctis", awakening: 1), // Magic Attack +20% (Vision)
    1275: CatalogSourceReference("Amelia", awakening: 1), // Magic Attack +30% (Vision)
    1395: CatalogSourceReference("Charlotte"), // Magic Barrier (Vision)
    1103: CatalogSourceReference("Laevateinn"), // Magic Boost (Equipment)
    1030: CatalogSourceReference("Cecil"), // Magic Counter (Vision)
    // 1036: Magic Counter — no assignment found.
    1083: CatalogSourceReference("Adar"), // Magic Counter with Selected Ability (Monster)
    1314: CatalogSourceReference("Book of Eibon"), // Magic Defense +10% (Equipment)
    1315: CatalogSourceReference("Cecil", awakening: 4), // Magic Defense +20% (Vision)
    1276: CatalogSourceReference("Dabih Warlock"), // Magic Defense +30% (Monster)
    1134: CatalogSourceReference("Elnath"), // Magic Defense +60% (Monster)
    1551: CatalogSourceReference("Illusory Robe"), // Magic Evade (S) (Equipment)
    1086: CatalogSourceReference("Cactuar"), // Magic Evasion (Monster)
    1445: CatalogSourceReference("Victoria"), // Mana Overload (Vision)
    1438: CatalogSourceReference("Lightning"), // Momentum Shift (Vision)
    1380: CatalogSourceReference("Tronn", awakening: 1), // MP +10% (Vision)
    1381: CatalogSourceReference("Ayaka", awakening: 3), // MP +20% (Vision)
    1382: CatalogSourceReference("Lordly Robes+"), // MP +30% (Equipment)
    // Studio passives, PDF page 30.
    1307: CatalogSourceReference("Shantotto"), // MP Stroll (Vision)
    1504: CatalogSourceReference("Victoria"), // MRP Gain +50% (Vision)
    1052: CatalogSourceReference("Dragon Seal"), // No Encounters (Equipment)
    1114: CatalogSourceReference("Vaan", awakening: 2), // Nullify Berserk (Vision)
    1105: CatalogSourceReference("Aileen", awakening: 2), // Nullify Blind (Vision)
    1111: CatalogSourceReference("Leah", awakening: 1), // Nullify Charm (Vision)
    1109: CatalogSourceReference("Victoria", awakening: 2), // Nullify Confuse (Vision)
    // 1115: Nullify Doom — no assignment found.
    1325: CatalogSourceReference("Ayaka", awakening: 3), // Nullify Instant Death (Vision)
    1080: CatalogSourceReference("Azure Pot"), // Nullify Magic (Monster)
    1108: CatalogSourceReference("Jeweled Ring"), // Nullify Paralysis (Equipment)
    1110: CatalogSourceReference("Jeweled Ring"), // Nullify Petrify (Equipment)
    1079: CatalogSourceReference("Amoebozoa"), // Nullify Physical (Monster)
    1104: CatalogSourceReference("Leah", awakening: 2), // Nullify Poison (Vision)
    1107: CatalogSourceReference("Ayaka", awakening: 2), // Nullify Silence (Vision)
    1106: CatalogSourceReference("Wilhelm", awakening: 3), // Nullify Sleep (Vision)
    1116: CatalogSourceReference("Onion Knight", awakening: 2), // Nullify Slow (Vision)
    1343: CatalogSourceReference("Vaan"), // Observe and Attack (Vision)
    // Studio passives, PDF page 31.
    1392: CatalogSourceReference("Aileen"), // Observe and Charge LB (Vision)
    1465: CatalogSourceReference("Onion Knight"), // Observe and Recover HP (Vision)
    1439: CatalogSourceReference("Lightning", awakening: 4), // Odin’s Blessing (Vision)
    1435: CatalogSourceReference("Vaan", awakening: 4), // One for the Road (Vision)
    1492: CatalogSourceReference("Sephiroth", awakening: 4), // One-Winged Angel (Vision)
    1437: CatalogSourceReference("Lightning"), // Overwhelm (Vision)
    1413: CatalogSourceReference("Cecil", awakening: 4), // Paladin’s Code (Vision)
    1493: CatalogSourceReference("Sephiroth"), // Perfect Serenity (Vision)
    1044: CatalogSourceReference("Leah"), // Pharmacology (Vision)
    1360: CatalogSourceReference("Noctis", awakening: 4), // Phase Echo (Vision)
    1308: CatalogSourceReference("Camille", awakening: 2), // Physical Attack +10% (Vision)
    1309: CatalogSourceReference("Camille", awakening: 1), // Physical Attack +20% (Vision)
    1273: CatalogSourceReference("Cecil", awakening: 1), // Physical Attack +30% (Vision)
    1029: CatalogSourceReference("Warrior of Light"), // Physical Counter (Vision)
    // 1035: Physical Counter — no assignment found.
    1082: CatalogSourceReference("Antlion"), // Physical Counter with Selected Ability (Monster)
    1312: CatalogSourceReference("Mythril Armor"), // Physical Defense +10% (Equipment)
    1313: CatalogSourceReference("Aileen", awakening: 3), // Physical Defense +20% (Vision)
    // Studio passives, PDF page 32.
    1274: CatalogSourceReference("Dabih Cultist"), // Physical Defense +30% (Monster)
    1085: CatalogSourceReference("Cactuar"), // Physical Evasion (Monster)
    1055: CatalogSourceReference("Brigand’s Gloves"), // Pickpocket’s Prowess (Equipment)
    1065: CatalogSourceReference("Vindemiatrix"), // Piercing Magic (Monster)
    1404: CatalogSourceReference("Aileen"), // Pilebunker (Vision)
    1433: CatalogSourceReference("Shantotto", awakening: 4), // Play Rough (Vision)
    1067: CatalogSourceReference("Poison Charm"), // Poison Powered (Equipment)
    1385: CatalogSourceReference("Clive"), // Power Stagger (Vision)
    1394: CatalogSourceReference("Camille"), // Preemptive Strike (Vision)
    1352: CatalogSourceReference("Leah", awakening: 4), // Preventive Care (Vision)
    1300: CatalogSourceReference("Leah", awakening: 3), // Protect at Half HP (Vision)
    1390: CatalogSourceReference("Aileen", awakening: 2), // Protect on Stagger (Vision)
    1290: CatalogSourceReference("Aileen", awakening: 4), // Protect Opener (Vision)
    1359: CatalogSourceReference("Tidus", awakening: 4), // Quick Hit (Vision)
    1459: CatalogSourceReference("Lightning", awakening: 1), // Radiant Knight (Vision)
    // 1471: Radiant Light — no assignment found.
    1383: CatalogSourceReference("Aileen"), // Rearguard (Vision)
    1338: CatalogSourceReference("Firion"), // Recuperate LB (Vision)
    // Studio passives, PDF page 33.
    // 1303: Reflect at Half HP — no assignment found.
    1257: CatalogSourceReference("Noctis"), // Reflex (Vision)
    1302: CatalogSourceReference("Elegant Robe"), // Regen at Half HP (Equipment)
    1286: CatalogSourceReference("Clive", awakening: 3), // Regen on Stagger (Vision)
    1293: CatalogSourceReference("Clive", awakening: 4), // Regen Opener (Vision)
    // 1240: Reinforcement Counter — no assignment found.
    1253: CatalogSourceReference("Warrior of Light", awakening: 3), // Resist Dark (Vision)
    1249: CatalogSourceReference("Camille", awakening: 2), // Resist Earth (Vision)
    1011: CatalogSourceReference("Clive", awakening: 2), // Resist Fire (Vision)
    1033: CatalogSourceReference("Charlotte", awakening: 2), // Resist Ice (Vision)
    1252: CatalogSourceReference("Scintillating Ring"), // Resist Light (Equipment)
    1250: CatalogSourceReference("Cloud", awakening: 2), // Resist Lightning (Vision)
    1251: CatalogSourceReference("Tidus", awakening: 2), // Resist Water (Vision)
    1248: CatalogSourceReference("Bartz", awakening: 2), // Resist Wind (Vision)
    // 1322: Restore HP on Critical Hit — no assignment found.
    1318: CatalogSourceReference("Clive"), // Restore HP on Defeating Foes (Vision)
    1284: CatalogSourceReference("Warrior of Light"), // Restore HP on Stagger (Vision)
    1124: CatalogSourceReference("Squall"), // Restore MP on Attack (Vision)
    // Studio passives, PDF page 34.
    1323: CatalogSourceReference("Cloud"), // Restore MP on Critical Hit (Vision)
    1319: CatalogSourceReference("Shantotto"), // Restore MP on Defeating Foes (Vision)
    1281: CatalogSourceReference("Tronn"), // Restore MP on Stagger (Vision)
    1356: CatalogSourceReference("Camille"), // Restore MP when Taking Damage (Vision)
    1355: CatalogSourceReference("Terra", awakening: 4), // Ribbon (Vision)
    1339: CatalogSourceReference("Wilhelm"), // Riposte (Vision)
    1399: CatalogSourceReference("Noctis"), // Scan and Strike (Vision)
    1441: CatalogSourceReference("Y’shtola", awakening: 4), // Scion Sorceress (Vision)
    1447: CatalogSourceReference("Aileen", awakening: 4), // Screwdriver (Vision)
    1332: CatalogSourceReference("Terra"), // Sharp Mind (Vision)
    // 1477: Shell and Protect on Stagger — no assignment found.
    1299: CatalogSourceReference("Warrior of Light", awakening: 2), // Shell at Half HP (Vision)
    // 1476: Shell on Stagger — no assignment found.
    1291: CatalogSourceReference("Y’shtola", awakening: 3), // Shell Opener (Vision)
    1450: CatalogSourceReference("Charlotte", awakening: 4), // Shield of Grandshelt (Vision)
    1418: CatalogSourceReference("Cloud", awakening: 4), // Signature Moves (Vision)
    1464: CatalogSourceReference("Y’shtola"), // Skill Flow (Vision)
    1326: CatalogSourceReference("Amelia"), // Skilled Disruptor (Vision)
    // Studio passives, PDF page 35.
    1434: CatalogSourceReference("Vaan", awakening: 1), // Skyward Dreams (Vision)
    1298: CatalogSourceReference("Impetus Breaker"), // Slow Opener (Equipment)
    1277: CatalogSourceReference("Ayaka", awakening: 2), // Speed +10% (Vision)
    1317: CatalogSourceReference("Amelia", awakening: 2), // Speed +20% (Vision)
    1316: CatalogSourceReference("Bartz"), // Speed +5% (Vision)
    1416: CatalogSourceReference("Bartz", awakening: 4), // Spellblade Mastery (Vision)
    1415: CatalogSourceReference("Bartz", awakening: 3), // Spellblade Wielder (Vision)
    1258: CatalogSourceReference("Onion Knight"), // Spry Steps (Vision)
    1278: CatalogSourceReference("Barrel Blazer"), // Stagger Power +10% (Equipment)
    1279: CatalogSourceReference("Cloud", awakening: 2), // Stagger Power +20% (Vision)
    1376: CatalogSourceReference("Aileen", awakening: 1), // Stagger Power +30% (Vision)
    1370: CatalogSourceReference("Y’shtola"), // Staggering Spells (Vision)
    1405: CatalogSourceReference("Cecil"), // Staggeringly Risky (Vision)
    1118: CatalogSourceReference("Rugged Whip"), // Stalwart Knight (Equipment)
    1396: CatalogSourceReference("Amelia"), // Stealth Specialist (Vision)
    1336: CatalogSourceReference("Wilhelm"), // Strategic Acumen (Vision)
    1461: CatalogSourceReference("Aileen", awakening: 1), // Supercharged Driver (Vision)
    // 1032: Talk Counter — no assignment found.
    // Studio passives, PDF page 36.
    1430: CatalogSourceReference("Terra"), // Tenebrous Rites (Vision)
    1040: CatalogSourceReference("Orbs of Light"), // Text-when-KO’d Counter (Monster)
    1432: CatalogSourceReference("Shantotto", awakening: 1), // The Federation’s Fiend (Vision)
    1393: CatalogSourceReference("Ayaka"), // The Hand That Heals (Vision)
    // 1475: The Power Within — no assignment found.
    1426: CatalogSourceReference("Zidane", awakening: 1), // Thievery (Vision)
    1451: CatalogSourceReference("Charlotte", awakening: 2), // Throw Down the Gauntlet (Vision)
    // 1028: Thunder Weapon — no assignment found.
    1428: CatalogSourceReference("Tidus"), // Tip-Top Shape (Vision)
    1387: CatalogSourceReference("Zidane", awakening: 4), // Treasure Hunter (Vision)
    1422: CatalogSourceReference("Squall"), // Trigger (Vision)
    1444: CatalogSourceReference("Amelia", awakening: 4), // Trigger-Happy (Vision)
    1406: CatalogSourceReference("Tronn", awakening: 4), // True Stagger (Vision)
    1494: CatalogSourceReference("Sephiroth"), // Ultimate Aggression (Vision)
    1417: CatalogSourceReference("Terra", awakening: 4), // Unlock Magic (Vision)
    1453: CatalogSourceReference("Wilhelm", awakening: 4), // Unmoving Bulwark (Vision)
    1239: CatalogSourceReference("Chocobo Nitro"), // Upgrade (Equipment)
    1340: CatalogSourceReference("Amelia"), // Versatility (Vision)
    // Studio passives, PDF page 37.
    1446: CatalogSourceReference("Victoria", awakening: 3), // Victori-ous Elixir (Vision)
    1372: CatalogSourceReference("Amelia", awakening: 2), // Victor’s Reprieve (Vision)
    1407: CatalogSourceReference("Tronn", awakening: 2), // Victor’s Respite (Vision)
    1048: CatalogSourceReference("Alarm Earrings"), // Vigilance (Equipment)
    1358: CatalogSourceReference("Onion Knight"), // Vigorous Attacks (Vision)
    1371: CatalogSourceReference("Clive"), // Vigorous Staggerer (Vision)
    1398: CatalogSourceReference("Necronomicon"), // Vital Strike (Equipment)
    1466: CatalogSourceReference("Noctis", awakening: 4), // Warp Crit (Vision)
    1348: CatalogSourceReference("Tidus"), // Water Eater (Vision)
    1367: CatalogSourceReference("Tidus", awakening: 4), // Water Immunity (Vision)
    1462: CatalogSourceReference("Camille", awakening: 1), // Water’s Protection (Vision)
    1329: CatalogSourceReference("Impact Wand"), // Weak Element Stagger Power +30% (Equipment)
    1373: CatalogSourceReference("Pilebunker"), // Weak Element Stagger Power +40% (Equipment)
    // 1374: Weak Element Stagger Power +50% — no assignment found.
    1099: CatalogSourceReference("Bullseye Mace"), // Weakness Exploiter (Equipment)
    // 1345: Wind Eater — no assignment found.
    // 1364: Wind Immunity — no assignment found.
    // Studio passives, PDF page 38.
    1436: CatalogSourceReference("Vaan", awakening: 4), // Wings of Freedom (Vision)
  },
};
